name: praktikum_state_mngmnt_2023

description: A new Flutter project.

publish_to: 'none' # Menandakan paket ini tidak akan dipublish ke pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 # Hapus duplikat dan pastikan versi yang benar

  # Cupertino Icons font untuk iOS style icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Paket rekomendasi lints untuk meningkatkan praktik coding
  flutter_lints: ^2.0.0

flutter:

  # Mengaktifkan penggunaan material design icons
  uses-material-design: true

  # Untuk menambahkan asset gambar ke aplikasi
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Menambahkan font kustom jika diperlukan
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
